Description: 'Template to generate the necessary IAM Policies for Jenkins-X EKS support '
Resources:
  CFNJenkinsXPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ "-", [ CNFTektonBotPolicy, Ref: PoliciesSuffixParameter] ] 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:ListStacks
          - cloudformation:DescribeStacks
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - eks:*
          - iam:DetachRolePolicy
          - iam:GetPolicy
          - iam:CreatePolicy
          - iam:DeleteRole
          - iam:GetOpenIDConnectProvider
          Resource: "*"
Parameters: 
  PoliciesSuffixParameter: 
    Type: String
    Description: A suffix so we can create different policies on each execution
Outputs:
  CFNTektonBotPolicy:
    Value:
      Ref: CFNJenkinsXPolicies
    Description: The ARN of the created policy
    Export:
      Name: !Join [ "-", [ TektonBotPolicy, Ref: PoliciesSuffixParameter] ] 
